name: test.yaml
on:
  pull_request: {}

jobs:
  nix_check:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
      - run: |
          nix flake check

  rust_check:
    runs-on: "ubuntu-latest"
    needs:
      - nix_check
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
      - run: |
          nix develop --command cargo clippy --all-targets -- --deny warnings

  ci_pass:
    if: ${{ always() }}
    runs-on: "ubuntu-latest"
    needs:
      - nix_check
      - rust_check
    steps:
      - name: check status
        uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJSON(needs) }}
